#!/bin/bash

#un script (bash, powershell, python) 
#5 consultas a una api donde al menos 2 
#sean consultas basadas en una consulta previa

api_key="2XvdpsxuTo1hyPJqEOr3CwLKF5Pxaq4ldaGdbqIy"
start_date="2021-09-14"
end_date="2021-09-14"
url="https://api.nasa.gov/neo/rest/v1/feed?start_date=$start_date&end_date=$end_date&api_key=$api_key"

#El script consulta el api de la NASA para ver los objetos(asteroides, meteoros, cometas, etc)
#mas cercanos a la tierra.
#Uso el programa jq para manejar la informacion de los jsons



echo "Objetos cercanos a la tierra: "

for i in {0..3}
do
	echo "**********************************************"
	echo "ID"
	id=$(curl -s $url | jq -r '.near_earth_objects | .[] | .['$i'] .id' )
	echo $id
	echo "Name"
	names=$(curl -s $url | jq -r '.near_earth_objects | .[] | .['$i'] | .name')
	echo $names
	echo "Is dangerous?"
	dang=$(curl -s $url | jq -r '.near_earth_objects | .[] | .['$i'] | .is_potentially_hazardous_asteroid')
	echo $dang
	if "$dang" == true
	then
		vel=$(curl -s $url | jq -r '.near_earth_objects | .[] | .['$i'] | .close_approach_data | .[] | .relative_velocity | .kilometers_per_hour')
		echo "Su velocidad es "$vel"km/h CUIDADOOO!!!"
		notice=$(curl -s $url | jq -r '.near_earth_objects | .[] | .['$i'] | .nasa_jpl_url ')
		echo "Ve informacion aqui: "$notice
	fi
done
